export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const GET_TRANSACTION = 'GET_TRANSACTION'
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
